// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');
require('./vendor/ember-data');
require('./templates');

var App = window.App = require('./app');

App.store = require('./store');

App.GuidesController = require('./controllers/guides_controller');
App.Guide = require('./models/guide');
App.GuidesRoute = require('./routes/guides_route');

require('./routes');

